spring:
  application:
    name: edm

---

spring:
  config:
    activate:
      on-profile: local
  cloud:
    vault:
      enabled: false
---

spring:
  config:
    activate:
      on-profile: test,dev
    import: vault://
  cloud:
    vault:
      enabled: true
      uri: ...
      authentication: AWS_IAM
      kv:
        backend: secrets
        default-context: ${spring.application.name}
