spring:
  application:
    name: edm
management:
  endpoints:
    enabled-by-defaults: false
  endpoint:
    health:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: local
  cloud:
    vault:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: test,dev
    import: vault://
  cloud:
    vault:
      enabled: true
      fail-fast: true
      uri: ${VAULT_URI}
      authentication: AWS_IAM
      kv:
        backend: secrets
        default-context: ${spring.application.name}
