spring:
  application:
    name: edm
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    vault:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: dev,stg,prd
    import: vault://
  cloud:
    vault:
      enabled: true
      fail-fast: true
      uri: https://${VAULT_HOST}
      authentication: AWS_IAM
      aws-iam:
        role: ${spring.profiles.active}-edm-role
        aws-path: aws
        server-name: ${VAULT_HOST}
        endpoint-uri: https://sts.ap-northeast-2.amazonaws.com
      kv:
        backend: secrets
        default-context: ${spring.application.name}
