spring:
  application:
    name: edm
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

---

spring:
  config:
    activate:
      on-profile: local
  cloud:
    vault:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: test,dev
    import: vault://
  cloud:
    vault:
      enabled: true
      fail-fast: true
      uri: ${VAULT_URI}
      authentication: AWS_IAM
      kv:
        backend: secrets
        default-context: ${spring.application.name}
